### ISSUE TITLE
detail method prints even when test succeeds

### ISSUE THREAD

**Issue by pepperskis** [test-bench/test-bench#11]
In the following test the detail method prints in both cases.

```
context "Test detail method" do
  test "Assert false" do
    detail "Detail prints"
    assert false
  end

  test "Assert true" do
    detail "Detail prints"
    assert true
  end
end
```

Example output
```
matthew.thorley@00735-matthew test-details-component % ./test.sh
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-darwin20]

TEST_BENCH_DETAIL: nil

Running test/automated/database_connection.rb
Database Connection
  Connects on first use
  This test is for example purposes. You may remove it once it has served its purpose.

Running test/automated/detail.rb
Test detail method
  Assert false
    Detail prints
    test/automated/detail.rb:9:in `block (2 levels) in <top (required)>': Assertion failed (TestBench::Fixture::AssertionFailure)
  Assert true
    Detail prints << Not expecting to see detail print here

Error Summary:
   1: test/automated/detail.rb
      test/automated/detail.rb:9:in `block (2 levels) in <top (required)>': Assertion failed (TestBench::Fixture::AssertionFailure)

Finished running 2 files
Ran 3 tests in 0.043s (69.8 tests/second)
2 passed, 0 skipped, 1 failed, 1 total error
```

Using test_bench-fixture 1.4.0.1
Using test_bench 1.2.0.8

**Comment by ntl** [comment]
I believe we worked through this issue in our Slack channel, so I'm a bit late with the reply here.

For posterity: the observed behavior is by design -- the details are shown for the entire test file when there is any failure. The rationale is that any information may be pertinent to diagnose a failure. If the file produces too much output, it is recommended to consider whether the file can be split into multiple individual files within a subdirectory.
